import * as THREE from 'three';
import { VRButton } from 'three/addons/webxr/VRButton.js';
import { AssetManager } from './core/AssetManager.js';
import { errors, levels } from './data/errors.js';
import '../styles/main.css';

const $=s=>document.querySelector(s), app=$('#app');
const saved=JSON.parse(localStorage.getItem('fiscal-save')||'{}');
const defaults={volume:.35,quality:'medium',sensitivity:.0025,smoothing:.12,gazeDuration:1,ipd:64,fov:75,invertY:false,highContrast:false,reducedMotion:false,muted:false};
const settings={...defaults,...saved.settings};
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:settings.quality!=='low',alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='high'?1.75:1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=settings.quality!=='low';renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.xr.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7c8c8');scene.fog=new THREE.Fog('#b7c8c8',13,30);
const camera=new THREE.PerspectiveCamera(settings.fov,innerWidth/innerHeight,.05,80);camera.position.set(0,1.65,5.7);
const player=new THREE.Group();player.position.set(0,0,5.7);scene.add(player);player.add(camera);camera.position.set(0,1.65,0);
const clock=new THREE.Clock(), raycaster=new THREE.Raycaster();
const state={running:false,level:1,score:0,lives:3,combo:0,bestCombo:0,found:0,falseCalls:0,missed:0,time:600,activeErrors:[],targets:[],selected:null,locked:false,mode:'desktop',debug:false,orientation:null,orientationZero:null,orientationScreen:0,permission:'unknown',fps:0,frameCount:0,elapsed:0,eventTimer:15,storage:null};
const mats={wall:new THREE.MeshStandardMaterial({color:'#dce5e0',roughness:.86}),floor:new THREE.MeshStandardMaterial({color:'#899598',roughness:.8}),cabinet:new THREE.MeshStandardMaterial({color:'#b8c3bd',roughness:.54}),steel:new THREE.MeshStandardMaterial({color:'#9aa8a7',metalness:.72,roughness:.3}),wood:new THREE.MeshStandardMaterial({color:'#ab8d6e',roughness:.7}),glass:new THREE.MeshPhysicalMaterial({color:'#b8d5d2',roughness:.12,metalness:.05,transmission:.45,transparent:true,opacity:.7}),white:new THREE.MeshStandardMaterial({color:'#f2eee0',roughness:.64}),blue:new THREE.MeshStandardMaterial({color:'#3b8490',roughness:.43}),red:new THREE.MeshStandardMaterial({color:'#a9493e',roughness:.55}),green:new THREE.MeshStandardMaterial({color:'#748d76',roughness:.68}),black:new THREE.MeshStandardMaterial({color:'#333c3d',roughness:.5})};
function box(parent,name,pos,size,mat,opts={}){const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);mesh.name=name;mesh.position.set(...pos);mesh.castShadow=mesh.receiveShadow=true;mesh.userData={...opts};parent.add(mesh);return mesh;}
function cylinder(parent,name,pos,rTop,rBot,h,mat,radial=16){const m=new THREE.Mesh(new THREE.CylinderGeometry(rTop,rBot,h,radial),mat);m.name=name;m.position.set(...pos);m.castShadow=true;parent.add(m);return m;}
function buildWorld(){
 const hemi=new THREE.HemisphereLight('#f2ffff','#746b5d',2.0);scene.add(hemi);const key=new THREE.DirectionalLight('#fff6dc',2.1);key.position.set(-4,8,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=10;key.shadow.camera.bottom=-10;scene.add(key);
 const ceilingLight=new THREE.PointLight('#d9f0ee',28,12);ceilingLight.position.set(0,3.5,0);scene.add(ceilingLight);
 box(scene,'Piso',[0,-.1,0],[12,.2,11],mats.floor);box(scene,'Parede traseira',[0,1.8,-5.4],[12,3.8,.2],mats.wall);box(scene,'Parede esquerda',[-6,1.8,0],[.2,3.8,11],mats.wall);box(scene,'Parede direita',[6,1.8,0],[.2,3.8,11],mats.wall);box(scene,'Parede frontal',[0,1.8,5.4],[4,3.8,.2],mats.wall);box(scene,'Teto',[0,3.8,0],[12,.15,11],mats.white);
 // Ceiling panels and cool laboratory finish.
 for(let x=-4;x<=4;x+=2.7){const p=box(scene,'Painel de iluminação',[x,3.69,-.5],[1.7,.025,.65],mats.white);p.material=new THREE.MeshBasicMaterial({color:'#fbfff6'});}
 // Independent cabinets, work surfaces, sink, shelves, refrigerator and instruments.
 for(let x=-4.25;x<=4.3;x+=1.7){box(scene,'Armário inferior',[x,.53,-4.6],[1.55,1.05,.7],mats.cabinet);box(scene,'Frente de gaveta',[x,.6,-4.2],[.65,.34,.035],mats.steel);box(scene,'Puxador',[x,.6,-4.16],[.2,.035,.04],mats.black);}
 box(scene,'Bancada',[0,1.15,-4.5],[9.5,.12,1.05],mats.steel);box(scene,'Tampo de bancada',[0,1.23,-4.5],[9.55,.08,1.08],mats.white);
 box(scene,'Cuba',[2.8,1.19,-4.48],[1.15,.025,.58],mats.black);box(scene,'Pia',[2.8,1.22,-4.48],[1.05,.035,.5],mats.steel);
 cylinder(scene,'Torneira',[2.8,1.49,-4.12],.035,.035,.42,mats.steel);box(scene,'Prateleira superior',[-2.1,2.65,-5.0],[4.6,.1,.42],mats.wood);box(scene,'Prateleira inferior',[-2.1,2.12,-5.0],[4.6,.1,.42],mats.wood);
 box(scene,'Geladeira',[4.65,1.55,-4.7],[1.35,3.0,.95],mats.white);box(scene,'Porta da geladeira',[4.65,1.57,-4.18],[1.2,2.77,.06],mats.cabinet);box(scene,'Visor temperatura',[4.35,2.45,-4.11],[.3,.14,.025],mats.black);
 // Mobile exam cart, desk, monitor, seats, waste containers and room props.
 box(scene,'Carrinho de exame',[-3,1.05,.1],[1.7,.1,.75],mats.steel);for(const [x,z] of [[-3.7,-.2],[-2.3,-.2],[-3.7,.4],[-2.3,.4]])cylinder(scene,'Rodízio',[x,.16,z],.1,.1,.2,mats.black,12);
 box(scene,'Mesa de registros',[3,1,-1],[1.8,.12,.85],mats.wood);box(scene,'Monitor',[3,1.55,-1.2],[.75,.52,.08],mats.black);box(scene,'Tela',[3,1.55,-1.15],[.68,.43,.012],new THREE.MeshBasicMaterial({color:'#78a7a3'}));
 for(const [x,z] of [[-4,2],[4,2]]){cylinder(scene,'Assento cadeira',[x,.52,z],.34,.34,.12,mats.blue);for(let a=0;a<4;a++){const t=a*Math.PI/2;cylinder(scene,'Pé cadeira',[x+Math.cos(t)*.23,.23,z+Math.sin(t)*.23],.025,.025,.55,mats.steel,8);}}
 cylinder(scene,'Lixeira',[5,.42,1.8],.29,.36,.78,mats.green);cylinder(scene,'Coletor perfurocortante',[-5,.55,-2.5],.23,.27,.8,mats.red);box(scene,'Porta saída',[5.85,1.3,3.7],[.08,2.6,1.5],mats.wood);
 // Build a detailed population of small separate, gaze-examinable 3D objects.
 const interactables=[];let n=0;const spots=[];
 for(const x of [-4.1,-3.4,-2.6,-1.7,-.8,.1,1.1,2.0,3.5,4.2])spots.push([x,1.35,-4.45]);
 for(let shelf=0;shelf<2;shelf++)for(const x of [-4.0,-3.3,-2.6,-1.9,-1.2,-.5])spots.push([x,2.31+shelf*.53,-4.97]);
 for(let i=0;i<40;i++){
  const [x,y,z]=spots[i%spots.length];const row=Math.floor(i/spots.length), xx=x+(row%2)*.12, yy=y+(row>1?.12:0);const mat=[mats.blue,mats.white,mats.green,mats.red,mats.wood][i%5], error=errors[i];
  const group=new THREE.Group();group.position.set(xx,yy,z);group.name=`${error.objectId} ${error.category.toLowerCase()}`;scene.add(group);
  const isBottle=i%3===0;let obj;
  if(isBottle){obj=cylinder(group,'Frasco',[0,.17,0],.12,.15,.34,mat);cylinder(group,'Tampa',[0,.38,0],.07,.07,.1,mats.white,12);}
  else {obj=box(group,'Embalagem',[0,.14,0],[.3,.28,.2],mat);box(group,'Etiqueta',[0,.15,.104],[.2,.12,.008],mats.white);}
  const main=group.children[0];main.userData={interactive:true,type:'medicine',id:error.objectId,inspectable:true,error,description:error.description,difficulty:error.difficulty};
  group.traverse(c=>{if(c.isMesh){c.userData.root=main;}});interactables.push(main);
 }
 // Nearby independent non-error props and a small articulated staff figure.
 for(let i=0;i<8;i++){const x=-4.7+i*1.3;const tray=box(scene,`Bandeja ${i+1}`,[x,1.31,-3.85],[.54,.025,.38],i%2?mats.blue:mats.white);cylinder(scene,`Frasco de reagente ${i+1}`,[x,1.48,-3.85],.08,.09,.3,i%2?mats.green:mats.glass);}
 const person=new THREE.Group();person.position.set(-1.4,0,-1.8);scene.add(person);cylinder(person,'Perna esquerda',[-.1,.48,0],.1,.12,.95,mats.blue);cylinder(person,'Perna direita',[.1,.48,0],.1,.12,.95,mats.blue);box(person,'Jaleco',[0,1.22,0],[.53,.72,.28],mats.white);cylinder(person,'Pescoço',[0,1.72,0],.09,.09,.12,mats.wood);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,18,14),mats.wood);head.position.set(0,1.94,0);person.add(head);box(person,'Crachá',[.15,1.36,.15],[.1,.14,.02],mats.blue);
 state.staff=person;state.targets=interactables;
}
buildWorld();const assets=new AssetManager(); // Models are optional; the procedural scene remains the functional fallback.

function save(){localStorage.setItem('fiscal-save',JSON.stringify({settings,best:saved.best||0,unlocked:saved.unlocked||1,lastLevel:state.level,stats:{played:(saved.stats?.played||0)+(!state.running?1:0)}}));}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2400);}
function showScreen(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeScreen(){$('#modal').classList.add('hidden');}
function beginGame(level=1){state.level=level;state.score=0;state.lives=3;state.combo=0;state.bestCombo=0;state.found=0;state.falseCalls=0;state.missed=0;state.time=levels[level-1].minutes*60;state.eventTimer=18;state.running=true;state.activeErrors=[];const pool=[...errors].sort(()=>Math.random()-.5);state.activeErrors=pool.slice(0,levels[level-1].count);state.activeErrors.forEach(e=>{const m=state.targets.find(x=>x.userData.id===e.objectId);if(m){m.userData.error=e;m.userData.isError=true;} });for(const m of state.targets)if(!state.activeErrors.includes(m.userData.error))m.userData.isError=false;
 $('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');$('#touchControls').classList.toggle('hidden',innerWidth>800);$('#levelLabel').textContent=`NÍVEL ${level}`;updateHud();toast('Inspeção iniciada. Observe os detalhes do ambiente.');renderer.setAnimationLoop(animate);}
function updateHud(){const mm=Math.floor(state.time/60),ss=Math.max(0,Math.floor(state.time%60));$('#timer').textContent=`${mm}:${String(ss).padStart(2,'0')}`;$('#timer').classList.toggle('critical',state.time<30);$('#score').textContent=state.score;$('#lives').textContent='♥ '.repeat(state.lives)+'♡ '.repeat(3-state.lives);$('#combo').textContent=`COMBO ×${[1,1.2,1.5,2,2.5][Math.min(state.combo,4)]}`;$('#found').textContent=`${state.found} / ${state.activeErrors.length} IRREGULARIDADES`;}
function endGame(won=false){state.running=false;state.missed=Math.max(0,state.activeErrors.length-state.found);renderer.setAnimationLoop(animate);const accuracy=Math.round(state.found/Math.max(1,state.found+state.falseCalls)*100),best=Math.max(saved.best||0,state.score),elapsed=levels[state.level-1].minutes*60-state.time; saved.best=best;saved.unlocked=Math.max(saved.unlocked||1,Math.min(5,state.level+(won?1:0)));save();$('#hud').classList.add('hidden');$('#touchControls').classList.add('hidden');showScreen(`<div class="eyebrow">${won?'INSPEÇÃO CONCLUÍDA':'TURNO ENCERRADO'}</div><h2>${won?'Excelente trabalho':'Fim da inspeção'}</h2><p>Pontuação final <b>${state.score}</b> · Erros encontrados <b>${state.found}</b> · Erros perdidos <b>${state.missed}</b> · Falsos apontamentos <b>${state.falseCalls}</b></p><p>Precisão <b>${accuracy}%</b> · Tempo <b>${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}</b> · Melhor combo <b>${state.bestCombo}</b> · Vidas <b>${state.lives}/3</b> · Nível ${state.level}</p><div class="modal-actions"><button class="primary" id="again">Jogar novamente</button>${state.level<5&&won?'<button id="next">Próximo nível</button>':''}<button id="toMenu">Menu principal</button></div>`);$('#again').onclick=()=>{closeScreen();beginGame(state.level);};$('#next')?.addEventListener('click',()=>{closeScreen();beginGame(state.level+1);});$('#toMenu').onclick=()=>{closeScreen();$('#menu').classList.remove('hidden');};}
function evidenceFor(e,abnormal){const evidence={VALIDADE:abnormal?'Validade impressa: 08/2024':'Validade impressa: 08/2027',TEMPERATURA:abnormal?'Leitura atual: 12,8 °C · faixa informada: 2–8 °C':'Leitura atual: 4,2 °C · faixa informada: 2–8 °C',DOCUMENTAÇÃO:abnormal?'Conferência diária: campo de hoje sem preenchimento':'Conferência diária: registro de hoje preenchido',MEDICAMENTOS:abnormal?'Lacre / identificação: há divergência com a ficha do lote':'Lacre / identificação: correspondem à ficha do lote',HIGIENE:abnormal?'Superfície / recipiente: há sinal de resíduo ou contato':'Superfície / recipiente: sem resíduo visível',EPI:abnormal?'Proteção observada: falta ou uso inadequado para a tarefa':'Proteção observada: adequada à tarefa',ARMAZENAMENTO:abnormal?'Condição observada: posição ou vizinhança incompatível':'Condição observada: local e vizinhança adequados',ORGANIZAÇÃO:abnormal?'Acesso e sequência: item fora da posição de rotina':'Acesso e sequência: posição de rotina preservada',DESCARTE:abnormal?'Identificação e nível do coletor: verificar segregação / capacidade':'Identificação e nível do coletor: segregação e capacidade corretas',SEGURANÇA:abnormal?'Circulação ou acesso de emergência: há obstrução':'Circulação e acesso de emergência: livres',EQUIPAMENTOS:abnormal?'Integridade / funcionamento: sinal requer conferência':'Integridade / funcionamento: dentro do esperado',AMBIENTE:abnormal?'Área próxima: observar condição ambiental e superfícies':'Área próxima: condição ambiental dentro do esperado'};return evidence[e?.category]||'Compare identificação, conservação, armazenamento e registro.';}
function inspect(obj){if(!obj?.userData.interactive)return;state.selected=obj;const e=obj.userData.error;$('#inspectTitle').textContent=`${obj.name}`;$('#inspectDescription').textContent='Observe o objeto de perto. Decida se há uma irregularidade.';$('#inspectClues').innerHTML=`<p><b>Tipo:</b> insumo farmacêutico</p><p><b>Evidência observada:</b> ${evidenceFor(e,!!obj.userData.isError)}</p><p><b>Verifique:</b> identificação, condição, armazenamento e contexto.</p>`;if(e){obj.userData.error=e;obj.userData.isError=state.activeErrors.some(x=>x.id===e.id);}
 $('#inspect').classList.remove('hidden');$('#normalBtn').onclick=()=>judge(false);$('#irregularBtn').onclick=()=>judge(true);}
function judge(flag){const o=state.selected,e=o?.userData.error,actual=!!o?.userData.isError;$('#inspect').classList.add('hidden');if(flag===actual){if(actual){state.found++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);const mul=[1,1.2,1.5,2,2.5][Math.min(state.combo-1,4)];state.score+=Math.round(e.reward*mul);o.userData.isError=false;o.material= new THREE.MeshStandardMaterial({color:'#d7d0b8',roughness:.68});toast(`Registro correto · +${Math.round(e.reward*mul)} pontos`);if(state.found>=state.activeErrors.length){updateHud();endGame(true);return;}}else{state.score+=10;toast('Verificação correta. +10 pontos');}}else{state.falseCalls++;state.combo=0;state.score-=flag?-100:-50;if(e?.critical){state.lives--;toast('Falha crítica: uma vida foi perdida.');}else toast('Decisão incorreta. Pontuação reduzida.');if(state.lives<=0){updateHud();endGame(false);return;}}state.selected=null;updateHud();}
$('#inspectBack').onclick=()=>$('#inspect').classList.add('hidden');$('#closeModal').onclick=closeScreen;$('#start').onclick=()=>beginGame(Math.min(saved.lastLevel||1,saved.unlocked||1));
$('#tutorial').onclick=()=>showScreen(`<div class="eyebrow">GUIA RÁPIDO</div><h2>Como jogar</h2><p><b>Desktop:</b> clique para capturar o mouse; WASD move, mouse olha, F inspeciona, Esc abre o menu, C centraliza a direção.</p><p><b>VR:</b> use o botão Enter VR se disponível. Sem controles, mire no objeto e confirme a inspeção. No celular, escolha Mobile VR e permita os sensores quando o navegador solicitar.</p><p>Inspecione os itens, avalie evidências e registre somente o que considerar irregular. Os indícios não são destacados no ambiente.</p><button class="primary" id="tutClose">Entendi</button>`);$('#modalBody').onclick=e=>{if(e.target.id==='tutClose')closeScreen();};
$('#settingsBtn').onclick=()=>showSettings();
function showSettings(){showScreen(`<div class="eyebrow">PREFERÊNCIAS LOCAIS</div><h2>Configurações</h2><div class="settings-grid"><label>Qualidade<select id="quality"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label><label>IPD<select id="ipd">${[58,60,62,64,66].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Campo de visão<select id="fov"><option>65</option><option>75</option><option>85</option></select></label><label>Gaze<select id="gazeDuration"><option value=".5">0,5 s</option><option value=".75">0,75 s</option><option value="1">1 s</option><option value="1.5">1,5 s</option><option value="2">2 s</option></select></label><label>Volume<input id="volume" type="range" min="0" max="1" step=".05"></label><label><input id="invertY" type="checkbox"> Inverter eixo Y</label><label><input id="reducedMotion" type="checkbox"> Reduzir movimento</label><label><input id="highContrast" type="checkbox"> Alto contraste</label></div><div class="modal-actions"><button id="mobilevr" class="primary">Ativar Mobile VR</button><button id="recenter">Calibrar / recentralizar</button><button id="saveSettings">Salvar</button></div>`);for(const k of ['quality','ipd','fov','gazeDuration','volume','invertY','reducedMotion','highContrast']){const el=$(`#${k}`);if(k==='invertY'||k==='reducedMotion'||k==='highContrast')el.checked=!!settings[k];else el.value=settings[k];}$('#saveSettings').onclick=()=>{for(const k of ['quality','ipd','fov','gazeDuration','volume'])settings[k]=k==='gazeDuration'||k==='volume'?Number($(`#${k}`).value):k==='ipd'||k==='fov'?Number($(`#${k}`).value):$(`#${k}`).value;for(const k of ['invertY','reducedMotion','highContrast'])settings[k]=$(`#${k}`).checked;camera.fov=settings.fov;camera.updateProjectionMatrix();document.body.classList.toggle('contrast',settings.highContrast);save();closeScreen();};$('#mobilevr').onclick=async()=>{closeScreen();await enableMobileVR();};$('#recenter').onclick=()=>{state.orientationZero=state.orientation;toast('Direção recalibrada.');};}
$('#diagBtn').onclick=()=>diagnostics();
function diagnostics(){const gl=renderer.getContext(),xr=navigator.xr,rows=[['WebGL',gl?'SUPPORTED':'NOT SUPPORTED'],['WebXR',xr?'SUPPORTED':'NOT SUPPORTED'],['immersive-vr','Checking…'],['DeviceOrientation','DeviceOrientationEvent'in window?'SUPPORTED':'NOT SUPPORTED'],['DeviceMotion','DeviceMotionEvent'in window?'SUPPORTED':'NOT SUPPORTED'],['HTTPS',isSecureContext?'SECURE':'NOT SECURE'],['GPU',gl?.getParameter(gl.RENDERER)||'Indisponível'],['Orientação',screen.orientation?.type||'Indisponível'],['VR session',renderer.xr.isPresenting?'ACTIVE':'INACTIVE'],['Permissão sensor',state.permission],['FPS',String(Math.round(state.fps))]];showScreen(`<div class="eyebrow">ESTADO DO DISPOSITIVO</div><h2>Diagnóstico do sistema</h2><div class="diagnostics">${rows.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}</div><button id="refreshDiag">Atualizar</button> <button id="diagDone" class="primary">Fechar</button>`);$('#refreshDiag').onclick=diagnostics;$('#diagDone').onclick=closeScreen;if(xr?.isSessionSupported)xr.isSessionSupported('immersive-vr').then(ok=>{const row=[...document.querySelectorAll('.diagnostics>div')].find(x=>x.firstElementChild.textContent==='immersive-vr');if(row)row.lastElementChild.textContent=ok?'AVAILABLE':'UNAVAILABLE';}).catch(()=>{});}
// WebXR sessions use tracking from XRManager; device orientation is exclusive to mobile stereo mode.
document.body.appendChild(VRButton.createButton(renderer,{optionalFeatures:['local-floor','bounded-floor','hand-tracking']}));
renderer.xr.addEventListener('sessionstart',()=>{state.mode='webxr';document.body.classList.remove('stereo');if(!state.running)beginGame(Math.min(saved.lastLevel||1,saved.unlocked||1));});renderer.xr.addEventListener('sessionend',()=>{state.mode='desktop';if(state.running){state.running=false;$('#hud').classList.add('hidden');$('#menu').classList.remove('hidden');}});
async function enableMobileVR(){if(!('DeviceOrientationEvent'in window)){toast('DeviceOrientation não é suportado neste dispositivo.');return;}if(!isSecureContext){toast('Mobile VR precisa de uma página HTTPS.');return;}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){state.permission=await DeviceOrientationEvent.requestPermission();if(state.permission!=='granted'){toast('Permissão negada. Habilite sensores nas configurações do navegador.');return;}}else state.permission='granted';window.addEventListener('deviceorientation',onOrientation,true);state.mode='mobile-vr';document.body.classList.add('stereo');toast('Mobile VR ativo. Vire o telefone para olhar ao redor.');}catch{state.permission='denied';toast('Não foi possível habilitar os sensores.');}}
function onOrientation(ev){if(ev.alpha==null)return;state.orientation={alpha:THREE.MathUtils.degToRad(ev.alpha),beta:THREE.MathUtils.degToRad(ev.beta||0),gamma:THREE.MathUtils.degToRad(ev.gamma||0)};state.orientationScreen=THREE.MathUtils.degToRad(screen.orientation?.angle||0);if(!state.orientationZero)state.orientationZero=state.orientation;}
function applyOrientation(){if(state.mode!=='mobile-vr'||renderer.xr.isPresenting||!state.orientation||!state.orientationZero)return;const o=state.orientation,z=state.orientationZero;let yaw=-(o.alpha-z.alpha),pitch=-(o.beta-z.beta),roll=-(o.gamma-z.gamma);yaw=THREE.MathUtils.euclideanModulo(yaw+Math.PI,Math.PI*2)-Math.PI;pitch=THREE.MathUtils.clamp(pitch,-1.1,1.1);const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(pitch,yaw,roll,'YXZ'));camera.quaternion.slerp(q,1-settings.smoothing);}
function move(dt){if(renderer.xr.isPresenting||!state.running)return;const speed=(keys.Shift?3.7:2.25)*dt,dir=new THREE.Vector3();if(keys.KeyW||keys.ArrowUp)dir.z-=1;if(keys.KeyS||keys.ArrowDown)dir.z+=1;if(keys.KeyA||keys.ArrowLeft)dir.x-=1;if(keys.KeyD||keys.ArrowRight)dir.x+=1;dir.normalize().applyQuaternion(player.quaternion);const old=player.position.clone();player.position.addScaledVector(dir,speed);player.position.x=THREE.MathUtils.clamp(player.position.x,-5.2,5.2);player.position.z=THREE.MathUtils.clamp(player.position.z,-4.8,5.0);const blockers=[[-4.25,-4.6,1.65,.9],[-2.55,-4.6,1.65,.9],[-.85,-4.6,1.65,.9],[.85,-4.6,1.65,.9],[2.55,-4.6,1.65,.9],[4.25,-4.6,1.65,.9],[0,-4.5,9.6,1.15],[-3,0,1.95,1.0],[3,-1,2.0,1.0],[4.65,-4.7,1.5,1.1]];for(const [x,z,w,d] of blockers){if(Math.abs(player.position.x-x)<w/2+.32&&Math.abs(player.position.z-z)<d/2+.32){player.position.x=old.x;player.position.z=old.z;break;}}}
const keys={};window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyF')selectTarget();if(e.code==='KeyC'){player.rotation.y=0;camera.rotation.set(0,0,0);state.orientationZero=state.orientation;toast('Câmera recentralizada.');}if(e.code==='F3'){$('#debug').classList.toggle('hidden');state.debug=!state.debug;}if(e.code==='Escape'&&state.running){state.running=false;$('#hud').classList.add('hidden');$('#menu').classList.remove('hidden');}});window.addEventListener('keyup',e=>keys[e.code]=false);
$('#world').addEventListener('click',()=>{if(state.running&&state.mode==='desktop')$('#world').requestPointerLock?.();else if(state.running)selectTarget();});window.addEventListener('mousemove',e=>{if(document.pointerLockElement===$('#world')&&state.running){player.rotation.y-=e.movementX*settings.sensitivity;camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x-e.movementY*settings.sensitivity*(settings.invertY?-1:1),-1.45,1.45);}});
function selectTarget(){if(!state.running)return;raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const hits=raycaster.intersectObjects(state.targets,true);if(hits.length){const m=hits[0].object.userData.root||hits[0].object;inspect(m);}else toast('Olhe diretamente para um objeto para examiná-lo.');}
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('touchstart',e=>{e.preventDefault();keys[{forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD'}[b.dataset.move]]=true;});b.addEventListener('touchend',()=>{keys[{forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD'}[b.dataset.move]]=false;});}
let gazeTarget=null,gazeStart=0;function animate(){const dt=Math.min(clock.getDelta(),.05);if(state.running){state.elapsed+=dt;state.time-=dt;if(state.time<=0){state.time=0;state.missed=state.activeErrors.length-state.found;endGame(false);}else{if(Math.floor(state.elapsed*2)!==Math.floor((state.elapsed-dt)*2))updateHud();state.eventTimer-=dt;if(state.eventTimer<=0){state.eventTimer=20+Math.random()*35;state.staff.rotation.y=Math.random()*Math.PI*2;state.staff.position.x=THREE.MathUtils.clamp(state.staff.position.x+(Math.random()-.5)*1.3,-3.8,3.8);if(Math.random()<.45){const light=scene.children.find(x=>x.isPointLight);light.intensity=5;setTimeout(()=>light.intensity=28,180+Math.random()*160);}}move(dt);applyOrientation();state.staff.position.y=.025*Math.sin(state.elapsed*2.1);raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const h=raycaster.intersectObjects(state.targets,true)[0];const target=h?(h.object.userData.root||h.object):null;if(target&&target.userData.interactive){if(target!==gazeTarget){gazeTarget=target;gazeStart=state.elapsed;}if(state.mode!=='desktop'){const g=$('#gaze');g.classList.remove('hidden');g.firstElementChild.style.setProperty('--progress',`${Math.min(1,(state.elapsed-gazeStart)/settings.gazeDuration)*360}deg`);if(state.elapsed-gazeStart>=settings.gazeDuration){g.classList.add('hidden');inspect(target);gazeTarget=null;}}else $('#prompt').textContent=`F: inspecionar ${target.name}`;}else{gazeTarget=null;$('#gaze').classList.add('hidden');if(state.running)$('#prompt').textContent=state.mode==='desktop'?'WASD mover · Mouse olhar · F inspecionar':'Mire para examinar';}}}
 if(state.debug){const v=player.position,q=camera.quaternion;$('#debug').textContent=`FPS ${Math.round(state.fps)} · Pos ${v.x.toFixed(2)}, ${v.y.toFixed(2)}, ${v.z.toFixed(2)} · Q ${q.x.toFixed(2)}, ${q.y.toFixed(2)}, ${q.z.toFixed(2)}, ${q.w.toFixed(2)} · ${gazeTarget?.name||'—'} · Nv ${state.level} · ${state.score} pts · XR ${renderer.xr.isPresenting}`;}
 if(state.mode==='mobile-vr'&&!renderer.xr.isPresenting){const w=innerWidth,h=innerHeight;renderer.setScissorTest(true);renderer.setScissor(0,0,Math.floor(w/2),h);renderer.setViewport(0,0,Math.floor(w/2),h);camera.aspect=(w/2)/h;camera.updateProjectionMatrix();const eye=.032*(settings.ipd/64);camera.position.x=-eye;camera.rotation.y-=eye*.08;renderer.render(scene,camera);camera.rotation.y+=eye*.16;renderer.setScissor(Math.floor(w/2),0,Math.ceil(w/2),h);renderer.setViewport(Math.floor(w/2),0,Math.ceil(w/2),h);renderer.render(scene,camera);camera.rotation.y-=eye*.08;camera.position.x=0;renderer.setScissorTest(false);}else{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setViewport(0,0,innerWidth,innerHeight);renderer.render(scene,camera);}
 state.frameCount++;if(state.frameCount%15===0){state.fps=15/dt;}
}
renderer.setAnimationLoop(animate);window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running)toast('Pausa rápida: inspeção suspensa em segundo plano.');});
$('#best').textContent=`RECORDE ${saved.best||0}`;
